CRUD/blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from . import views

app_name="blog"
urlpatterns = [
    path('', MainpageView.as_view(), name='mainpage'),
    path('layout/', views.layout, name='layout'),
    path('blog/<int:blog_id>/comment', views.detail, name="detail"),
    path('blog/home/', views.home, name='home'),
    # path('new/', views.new, name='new'),
    # path('create/', views.create, name='create'),
    path('newblog/', views.blogform, name='newblog'),
    path('<int:blog_id>/edit/', views.edit, name='edit'),
    path('<int:blog_id>/remove/',views.remove, name='remove'),
    path('<int:blog_id>/<int:comment_id>/edit_comment/', views.edit_comment, name='edit_comment'),
    path('<int:blog_id>/<int:comment_id>/remove_comment/', views.remove_comment, name='remove_comment'),
    path('blog/hashtag/', views.hashtagform, name='hashtag'),
    path('<int:hashtag_id>/search/', views.search, name='search'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path,include
import blog.views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

CRUD/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    Hashtags = models.ManyToManyField('Hashtag', blank=True) # Hashtag 모델
    image = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog_id = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name="comments")
    comment_text = models.CharField(max_length=50)

    def __str__(self):
        return self.comment_text

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

CRUD/blog/forms.py
from django import forms
from .models import Blog, Comment, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [ 'title', 'body', 'Hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

CRUD/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic. base import TemplateView
from .forms import BlogForm, CommentForm, HashtagForm
from .models import Blog, Comment, Hashtag
# Create your views here.
def layout(request):
    return render(request, 'blog/layout.html')

def home(request):
    blogs = Blog.objects
    hashtags = Hashtag.objects
    return render(request, 'blog/home.html', {'blogs': blogs, 'hashtags':hashtags})

class MainpageView(TemplateView):
    template_name = 'blog/main.html'
    
def detail(request, blog_id, comment=None): #근데 여기에 굳이 None을 왜해준거지?
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog_id = blog
            comment.comment_text = form.cleaned_data["comment_text"]
            comment.save()
            return redirect("blog:detail", blog_id)        
    else:
        form = CommentForm(instance=comment)
        return render(request, "blog/detail.html",{"blog":blog, "form":form})

def blogform(request, blog_id=None):
    if request.method =='POST':
        form = BlogForm(request.POST, request.FILES, instance=blog_id)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.pub_date=timezone.now()
            blog.save()
            form.save_m2m()
            return redirect('blog:home')
    else:
        form = BlogForm(instance=blog_id)
        return render(request, 'blog/new.html', {'form':form})

def edit(request,blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return blogform(request, blog) #blogform 함수를 호출 리턴

def remove(request, blog_id):
    blog =get_object_or_404(Blog, id=blog_id)
    blog.delete()
    return redirect('blog:home')

def edit_comment(request, blog_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    return detail(request, blog_id, comment)

def remove_comment(request, blog_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('blog:detail', blog_id)
    
def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag=form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그"
                return render(request, 'blog/hashtag.html',{'form':form, "error_message":error_message})
            else:
                hashtag.name=form.cleaned_data['name']
                hashtag.save()
                return redirect('blog:home')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html', {'form':form})

def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'blog/search.html', {'hashtag':hashtag})

CRUD/blog/templates/blog/detail.html
{% extends 'blog/layout.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h6 class="display-4">제목 </h6>
            <p>{{ blog.title }}</p>
            <br><br>
            <p class="lead">내용<br><br>{{ blog.body }}</p>
            <br><br>
            {% if blog.image %}
                <p class="lead">사진<br><br>
                    <img src="{{ blog.image.url }}" alt="card image" style="max-width: 100%; height: auto;">
                </p>
            {% endif %}
            <hr class="my-4">
            <p>만든 날짜: {{ blog.pub_date }}</p>
            {% for hashtag in blog.Hashtags.all %}
            <span>{{ hashtag.name }}</span>
            {% endfor %}
            <br>
            <a class="btn btn-secondary" href="{% url 'blog:edit' blog.id %}" role="button">수정</a>
            <a class="btn btn-danger" href="{% url 'blog:remove' blog.id %}" role="button">삭제</a>
        </div>
        <div class ="jumbotron jumbotron-fluid">
            <div class="container">
                <p class="display-4">댓글<br></p>
                {% for comment in blog.comments.all %}
                <p class="lead">{{ comment.comment_text }}
                <a class="btn btn-secondary" href="{% url 'blog:edit_comment' blog.id comment.id %}" role="button">수정</a>
                <a class="btn btn-danger" href="{% url 'blog:remove_comment' blog.id comment.id %}" role="button">삭제</a>
                </p>
                {% endfor %}

            </div>
        </div>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

CRUD/blog/templates/blog/hashtag.html
{% extends 'blog/layout.html' %}

{% block header %}
<header class="masthead" >
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>new hashtag</h1>
            <span class="subheading">해시태그 추가하는 페이지.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock %}
  
  {% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{ error_message }}
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

CRUD/blog/templates/blog/home.html
{% extends 'blog/layout.html' %}

{% block content %}
<div class="container1">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hashtag 검색!
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          {% for hashtag in hashtags.all %}
          <a class="dropdown-item" href="{% url 'blog:search' hashtag.id %}" >{{ hashtag.name }}</a>
          {% endfor %}
        </div>
      </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">pk!</th>
        <th scope="col">Title</th>
        <th scope="col">time</th>
      </tr> 
    </thead>
    <tbody>
        {% for blog in blogs.all %}
      <tr>
        <br>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'blog:detail' blog.id %}">{{blog.title}}</a></td>
        <td>{{blog.pub_date}}</td>
        <br>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>

{% endblock %}

CRUD/blog/templates/blog/layout.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/layout.css' %}">
    <title>CRUD</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Likelion</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'blog:home' %}">게시판 <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'blog:newblog' %}">글쓰기</a>
        <a class="nav-item nav-link" href="{% url 'blog:hashtag' %}">해시태그</a>

        </div>
    </div>
    </nav>
    {% block header %}
    {% endblock %}
    
    {% block content %}
    {% endblock %}
    <footer>
        <div class="container1"></div>
          <p>Copyright &copy; Likelion, 2017</p>
        </div>
      </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

CRUD/blog/templates/blog/main.html
{% extends 'index.html' %}

CRUD/blog/templates/blog/new.html
{% extends 'blog/layout.html' %}

{% block content %}
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %} 
        
        <table id="ta">
            {{form.as_table}}
        </table>
        <input type="submit" value="제출하기" class="btn btn-dark">
    </form>
{% endblock %}

CRUD/blog/templates/blog/search.html
{% extends 'blog/layout.html' %}
{% block header %}
<!-- Page Header -->
<header class="masthead">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>{{ hashtag }}가 있는 게시글 목록</h1>
          <span class="subheading">해시태그 검색 결과 페이지.</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
{% block content %}
{% for blog in hashtag.blog_set.all %}
<div class="container1">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">pk!</th>
        <th scope="col">Title</th>
        <th scope="col">time</th>
      </tr> 
    </thead>
      <br><br><br>
    <tbody>
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'blog:detail' blog.id %}">{{blog.title}}</a></td>
        <td>{{blog.pub_date}}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endfor %}
{% endblock %}

CRUD/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CRUD</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/">Home</a>
      
      </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <h1 class="mx-auto my-0 text-uppercase">CRUD</h1>
        <h2 class="text-white-50 mx-auto mt-2 mb-5">CREATE READ UPDATE DELETE</h2>
        <a href="blog/home/" class="btn btn-primary js-scroll-trigger">Get Start CRUD!</a>
      </div>
    </div>
  </header>


</body>

</html>